import numpy as np

A = np.array([[1, 2], [3, -1]])
B = np.array([[-2, -2], [4, -3]])

ans_a = A+2*B
ans_b1 = np.matmul(A, B)
ans_b2 = np.matmul(B, A)
ans_c = A.transpose()
ans_d = np.matmul(B, B)
ans_e1 = np.matmul(A.transpose(), B.transpose())
ans_e2 = ans_b1.transpose()
ans_f = np.linalg.det(A)
ans_g = np.linalg.inv(B)

print("a.")
print(ans_a)
print("b1.")
print(ans_b1)
print("b2.")
print(ans_b2)
print("c.")
print(ans_c)
print("d.")
print(ans_d)
print("e1.")
print(ans_e1)
print("e2.")
print(ans_e2)
print("f.")
print(ans_f)
print("g.")
np.set_printoptions(precision=3, suppress=True)
print(ans_g)
